import { test, expect } from '@playwright/test'

const field = (page, label) => page.getByLabel(label, { exact: true })
const result = page => page.locator('.result-value')
async function usedA(page) {
  await field(page, '主机写入预算').fill('128')
  await field(page, '卡片状态').selectOption('used')
  await field(page, '全寿命累计 Host Writes').fill('18.5')
  await field(page, '日均写入').fill('35')
  await page.getByRole('button', { name: '开始计算', exact: true }).click()
  await expect(result(page)).toHaveText('8.6 年')
}
test.beforeEach(async ({ page }) => { await page.goto('./') })

test('empty form, field errors, first error focus, and numeric input preservation', async ({ page }) => {
  await expect(field(page, '主机写入预算')).toHaveValue('')
  await expect(field(page, '日均写入')).toHaveValue('')
  await page.getByRole('button', { name: '开始计算', exact: true }).click()
  await expect(field(page, '主机写入预算')).toBeFocused()
  await expect(field(page, '卡片状态')).toHaveAttribute('aria-invalid', 'true')
  await field(page, '主机写入预算').fill('-5')
  await field(page, '日均写入').fill('Infinity')
  await page.getByRole('button', { name: '开始计算', exact: true }).click()
  await expect(field(page, '主机写入预算')).toHaveValue('-5')
  await expect(field(page, '日均写入')).toHaveValue('Infinity')
  await expect(result(page)).toHaveText('—')
})
test('A dirty snapshot, Enter recalculation, invalid submission and live status', async ({ page }) => {
  await usedA(page)
  const initialChart = await page.getByRole('img', { name: /^写入量投影：/ }).getAttribute('aria-label')
  const initialProcess = await page.locator('.steps').innerText()
  await field(page, '日均写入').fill('70')
  await expect(page.locator('.chip')).toHaveText('待重新计算')
  await expect(result(page)).toHaveText('8.6 年')
  await expect(page.getByRole('img', { name: /^写入量投影：/ })).toHaveAttribute('aria-label', initialChart)
  await expect(page.locator('.steps')).toHaveText(initialProcess, { useInnerText: true })
  await field(page, '日均写入').press('Enter')
  await expect(result(page)).toHaveText('4.3 年')
  await expect(page.locator('.result-facts')).toContainText('109.5 TB')
  await field(page, '日均写入').fill('-1')
  await field(page, '日均写入').press('Enter')
  await expect(result(page)).toHaveText('4.3 年')
  await expect(page.locator('.sr-only[role="status"]')).toContainText('计算未更新')
})
test('D two inputs, optional candidate, disclosure retention and used/unknown candidates', async ({ page }) => {
  await page.getByRole('button', { name: '选型需求', exact: true }).click()
  await field(page, '目标年限').fill('5')
  await field(page, '日均写入').fill('35')
  await page.getByRole('button', { name: '开始计算', exact: true }).click()
  await expect(result(page)).toHaveText('63.9 TB')
  await expect(page.locator('.threshold-label')).toHaveCount(0)
  await page.getByText('比较候选卡（可选）', { exact: true }).click()
  await expect(page.locator('.chip')).toHaveText('假设情景')
  await field(page, '候选主机写入预算').fill('128')
  await page.getByRole('button', { name: '重新计算', exact: true }).click()
  await expect(page.locator('.result-facts')).toContainText('+64.1 TB')
  await page.getByText('比较候选卡（可选）', { exact: true }).click()
  await expect(result(page)).toHaveText('63.9 TB')
  await page.getByText('比较候选卡（可选）', { exact: true }).click()
  await expect(field(page, '候选主机写入预算')).toHaveValue('128')
  await field(page, '候选卡状态').selectOption('unknown')
  await page.getByRole('button', { name: '重新计算', exact: true }).click()
  await expect(page.locator('.threshold-label')).toHaveCount(0)
  await expect(page.locator('.budget')).toContainText('候选历史未知')
})
test('B measured NAND and separate historical WAF modal', async ({ page }) => {
  await page.getByRole('button', { name: 'P/E 工程估算（高级）', exact: true }).click()
  await field(page, '有效循环容量').fill('32'); await field(page, 'P/E 上限').fill('3000')
  await field(page, '已经消耗的写入量来源').selectOption('nand')
  await field(page, '全寿命 NAND 写入').fill('38.4'); await field(page, '未来 WAF').fill('2'); await field(page, '日均写入').fill('35')
  await page.getByRole('button', { name: '开始计算', exact: true }).click()
  await expect(result(page)).toHaveText('2.3 年'); await expect(page.locator('.result-facts')).toContainText('28.8 TB')
  await page.getByRole('button', { name: '没有 NAND 计数？使用历史 WAF 估算', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('全寿命累计 Host Writes', { exact: true }).fill('9.6')
  await dialog.getByLabel('全历史 WAF', { exact: true }).fill('4')
  await dialog.getByRole('button', { name: '采用估算', exact: true }).click()
  await expect(field(page, '未来 WAF')).toHaveValue('2')
  await page.getByRole('button', { name: '重新计算', exact: true }).click()
  await expect(result(page)).toHaveText('2.3 年'); await expect(page.locator('.steps')).toContainText('38.4 TB NAND')
})
test('mode and theory navigation preserve values; reset affects only current mode', async ({ page }) => {
  await usedA(page)
  await page.getByRole('button', { name: '选型需求', exact: true }).click()
  await field(page, '目标年限').fill('7')
  await page.getByRole('button', { name: '计算原理', exact: true }).click()
  await page.getByRole('button', { name: '计算分析', exact: true }).click()
  await expect(field(page, '目标年限')).toHaveValue('7')
  await page.getByRole('button', { name: '重置', exact: true }).click()
  await expect(field(page, '目标年限')).toHaveValue('')
  await page.getByRole('button', { name: '写入预算', exact: true }).click()
  await expect(field(page, '全寿命累计 Host Writes')).toHaveValue('18.5')
  await expect(result(page)).toHaveText('8.6 年')
})
test('advanced draft cancel/close/Esc, save and focus return', async ({ page }) => {
  await usedA(page)
  const trigger = page.getByRole('button', { name: '高级设置（可选）', exact: true })
  await trigger.click()
  await page.getByText('来源与测量记录（可选）', { exact: true }).click()
  await field(page, '资料来源').fill('https://example.com/cancelled')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await expect(trigger).toBeFocused()
  await trigger.click(); await page.getByText('来源与测量记录（可选）', { exact: true }).click()
  await expect(field(page, '资料来源')).toHaveValue('')
  await field(page, '资料来源').fill('Esc draft')
  await field(page, '资料来源').press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0); await expect(trigger).toBeFocused()
  await trigger.click(); await page.getByText('来源与测量记录（可选）', { exact: true }).click()
  await expect(field(page, '资料来源')).toHaveValue('')
  await field(page, '资料来源').fill('user test report 17')
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await expect(page.locator('.chip')).toHaveText('待重新计算')
  await page.getByRole('button', { name: '重新计算', exact: true }).click()
  await page.getByText('来源与适用范围（本次快照）', { exact: true }).click()
  await expect(page.locator('.records')).toContainText('user test report 17')
})
test('anchored help opens, closes, reopens and navigates to principles', async ({ page }) => {
  const trigger = page.getByRole('button', { name: '帮助：主机写入预算', exact: true })
  await trigger.press('Enter')
  await expect(page.getByRole('dialog')).toContainText('不是卡片容量')
  await page.getByRole('button', { name: '关闭', exact: true }).press('Escape')
  await expect(trigger).toBeFocused()
  await trigger.click(); await page.getByRole('button', { name: '查看计算原理', exact: true }).click()
  await expect(page.locator('#theory-host')).toBeVisible()
  await page.getByRole('button', { name: '计算分析', exact: true }).click()
  await trigger.click(); await page.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(trigger).toBeFocused()
})
test('genuine presets preserve missing parameters and require explicit assumptions', async ({ page }) => {
  await page.getByRole('button', { name: '工业卡', exact: true }).click()
  await field(page, '卡片型号 / 容量（可选）').selectOption('kingston-sdcit2-128gb')
  await expect(field(page, '主机写入预算')).toHaveValue('3840')
  await expect(page.locator('.preset-facts')).toContainText('3,840 TB')
  await page.getByRole('checkbox', { name: '将厂商 TBW 作为本次主机写入预算假设', exact: true }).check()
  await expect(field(page, '主机写入预算')).toHaveValue('3840')
  await field(page, '主机写入预算').fill('3000')
  await expect(page.locator('.preset-facts')).toContainText('参数已手改')
  await page.getByRole('button', { name: '高耐久卡', exact: true }).click()
  await field(page, '卡片型号 / 容量（可选）').selectOption('samsung-pro-endurance-2022-128gb')
  await expect(field(page, '主机写入预算')).toHaveValue('')
  await expect(page.locator('.preset-facts')).toContainText('70,080 小时')
  await page.getByRole('button', { name: 'P/E 工程估算（高级）', exact: true }).click()
  await page.getByText('型号参考（可选）', { exact: true }).click()
  await page.getByRole('button', { name: '工业卡', exact: true }).click()
  await field(page, '卡片型号 / 容量（可选）').selectOption('kingston-sdcit2-128gb')
  await expect(field(page, 'P/E 上限')).toHaveValue('30000')
  await expect(field(page, '有效循环容量')).toHaveValue('')
  await expect(field(page, '未来 WAF')).toHaveValue('')
})
test('unknown history, zero load and budget reached do not claim failure or infinite lifetime', async ({ page }) => {
  await field(page, '主机写入预算').fill('128'); await field(page, '卡片状态').selectOption('unknown'); await field(page, '日均写入').fill('35')
  await page.getByRole('button', { name: '开始计算', exact: true }).click()
  await expect(result(page)).toHaveText('暂不能估算'); await expect(page.locator('.chart')).toHaveCount(0)
  await field(page, '卡片状态').selectOption('new'); await field(page, '日均写入').fill('0')
  await page.getByRole('button', { name: '重新计算', exact: true }).click()
  await expect(page.locator('.result-panel')).toContainText('无法推算时间')
  await field(page, '卡片状态').selectOption('used'); await field(page, '全寿命累计 Host Writes').fill('150')
  await page.getByRole('button', { name: '重新计算', exact: true }).click()
  await expect(result(page)).toHaveText('预算已达到'); await expect(page.locator('.result-panel')).toContainText('不能判定')
})
test('custom identity is optional metadata and survives calculations and source snapshots', async ({ page }) => {
  await field(page, '卡片型号（可选）').fill('我的 16 GB 卡')
  await field(page, '标称容量（可选）').fill('16')
  await usedA(page)
  await page.getByText('来源与适用范围（本次快照）', { exact: true }).click()
  await expect(page.locator('.records')).toContainText('我的 16 GB 卡 · 16 GB')
  await page.getByRole('button', { name: '自定义', exact: true }).click()
  await expect(field(page, '卡片型号（可选）')).toHaveValue('我的 16 GB 卡')
  await expect(page.locator('.chip')).toHaveText('假设情景')
  await field(page, '标称容量（可选）').fill('-16')
  await page.getByRole('button', { name: '重新计算', exact: true }).click()
  await expect(field(page, '标称容量（可选）')).toBeFocused()
  await expect(result(page)).toHaveText('8.6 年')
})

test('budget methods occupy the same position and preserve their independent data', async ({ page }) => {
  await usedA(page)
  const initialBounds = await page.getByRole('group', { name: '预算方法', exact: true }).boundingBox()
  await page.getByRole('button', { name: 'P/E 工程估算（高级）', exact: true }).click()
  await expect(page.locator('.method-section')).toContainText('普通用户优先')
  const peBounds = await page.getByRole('group', { name: '预算方法', exact: true }).boundingBox()
  expect(peBounds.y).toBe(initialBounds.y)
  await page.getByRole('button', { name: '主机 TBW（常用）', exact: true }).click()
  await expect(field(page, '主机写入预算')).toHaveValue('128')
  await expect(result(page)).toHaveText('8.6 年')
})

test('factory budget is autofilled and adopted once; filters preserve identity, and a new capacity replaces only known specs', async ({ page }) => {
  await page.getByRole('button', { name: '工业卡', exact: true }).click()
  await field(page, '品牌筛选').selectOption('Transcend')
  await field(page, '容量筛选').selectOption('8')
  await field(page, '卡片型号 / 容量（可选）').selectOption('transcend-usd230i-8gb')
  await expect(field(page, '主机写入预算')).toHaveValue('360')
  await expect(field(page, '卡片状态')).toHaveValue(''); await expect(field(page, '日均写入')).toHaveValue('')
  await field(page, '卡片状态').selectOption('new'); await field(page, '日均写入').fill('100')
  await page.getByRole('button', { name: '开始计算', exact: true }).click()
  const confirmation = page.getByRole('checkbox', { name: '将厂商 TBW 作为本次主机写入预算假设', exact: true })
  await expect(confirmation).toBeFocused(); await confirmation.check()
  await page.getByRole('button', { name: '开始计算', exact: true }).click()
  await expect(result(page)).toHaveText('9.9 年')
  await page.getByRole('button', { name: '消费卡', exact: true }).click()
  await expect(page.locator('.chip')).toHaveText('假设情景')
  await expect(page.locator('.preset-name')).toContainText('USD230I')
  await expect(field(page, '主机写入预算')).toHaveValue('360')
  await field(page, '品牌筛选').selectOption('KIOXIA'); await field(page, '容量筛选').selectOption('16')
  await field(page, '卡片型号 / 容量（可选）').selectOption('kioxia-exceria-16gb')
  await expect(field(page, '主机写入预算')).toHaveValue('')
  await expect(field(page, '卡片状态')).toHaveValue('new'); await expect(field(page, '日均写入')).toHaveValue('100')
  await expect(page.locator('.preset-facts')).toContainText('主机 TBW 或 P/E')
  await expect(page.getByRole('checkbox')).toHaveCount(0)
})

test('P/E provenance remains while browsing filters; switching explicitly to custom removes the untouched factory cycles', async ({ page }) => {
  await page.getByRole('button', { name: 'P/E 工程估算（高级）', exact: true }).click()
  await page.getByText('型号参考（可选）', { exact: true }).click()
  await page.getByRole('button', { name: '工业卡', exact: true }).click()
  await field(page, '卡片型号 / 容量（可选）').selectOption('kingston-sdcit2-16gb')
  await expect(field(page, 'P/E 上限')).toHaveValue('30000')
  await page.getByRole('button', { name: '消费卡', exact: true }).click()
  await expect(field(page, 'P/E 上限')).toHaveValue('30000')
  await expect(page.locator('.preset-name')).toContainText('16 GB')
  await page.getByRole('button', { name: '自定义', exact: true }).click()
  await expect(field(page, 'P/E 上限')).toHaveValue('')
  await expect(page.locator('.preset-facts')).toHaveCount(0)
})

test('B reference selection retains authored pool and both WAF values, with explicit input provenance', async ({ page }) => {
  await page.getByRole('button', { name: 'P/E 工程估算（高级）', exact: true }).click()
  await field(page, '有效循环容量').fill('32'); await field(page, '未来 WAF').fill('2')
  await field(page, '已经消耗的写入量来源').selectOption('estimate')
  await field(page, '全寿命累计 Host Writes').fill('9.6'); await field(page, '全历史 WAF').fill('4'); await field(page, '日均写入').fill('35')
  await page.getByText('型号参考（可选）', { exact: true }).click()
  await expect(page.locator('.card-identity + .hint')).toContainText('不能代替有效循环容量')
  await expect(page.locator('.card-identity + .hint')).not.toContainText('下方')
  await page.getByRole('button', { name: '工业卡', exact: true }).click()
  await field(page, '卡片型号 / 容量（可选）').selectOption('kingston-sdcit2-16gb')
  await expect(field(page, '有效循环容量')).toHaveValue('32')
  await expect(field(page, '未来 WAF')).toHaveValue('2'); await expect(field(page, '全历史 WAF')).toHaveValue('4')
  await expect(field(page, 'P/E 上限')).toHaveValue('30000')
  await expect(page.locator('.preset-facts')).toContainText('由你提供，请核对')
  await page.getByRole('button', { name: '开始计算', exact: true }).click()
  await page.getByText('来源与适用范围（本次快照）', { exact: true }).click()
  await expect(page.locator('.records')).toContainText('来自你填写的假设或测量记录')
})

test('remaining label stays together across 672/671/670px for A and B budgets', async ({ page }) => {
  const labelTops = () => page.locator('.budget-value').evaluate(element => {
    const node = element.firstChild
    const start = node.textContent.indexOf('剩余')
    return [0, 1].map(offset => { const range = document.createRange(); range.setStart(node, start + offset); range.setEnd(node, start + offset + 1); return range.getBoundingClientRect().top })
  })
  await usedA(page)
  for (const width of [672, 671, 670]) { await page.setViewportSize({ width, height: 1000 }); const [first, second] = await labelTops(); expect(second).toBe(first) }
  await page.getByRole('button', { name: 'P/E 工程估算（高级）', exact: true }).click()
  await field(page, '有效循环容量').fill('32'); await field(page, 'P/E 上限').fill('3000')
  await field(page, '已经消耗的写入量来源').selectOption('nand'); await field(page, '全寿命 NAND 写入').fill('38.4')
  await field(page, '未来 WAF').fill('2'); await field(page, '日均写入').fill('35')
  await page.getByRole('button', { name: '开始计算', exact: true }).click()
  for (const width of [672, 671, 670]) { await page.setViewportSize({ width, height: 1000 }); const [first, second] = await labelTops(); expect(second).toBe(first) }
})

test('unknown history gives known facts and preserves snapshots; explicit planning action carries only the daily load', async ({ page }) => {
  await page.getByRole('button', { name: '选型需求', exact: true }).click()
  await field(page, '目标年限').fill('5'); await field(page, '日均写入').fill('19')
  await page.getByRole('button', { name: '写入预算', exact: true }).click()
  await field(page, '主机写入预算').fill('128'); await field(page, '卡片状态').selectOption('unknown'); await field(page, '日均写入').fill('35')
  await page.getByRole('button', { name: '开始计算', exact: true }).click()
  await expect(page.locator('.result-facts')).toContainText('128 TB')
  await expect(page.locator('.result-facts')).toContainText('12.775 TB/年')
  await expect(page.locator('.sensitivity')).toHaveCount(0)
  await expect(page.locator('.result-panel')).not.toContainText('— TB')
  const action = page.getByRole('button', { name: '带入此负载算选型需求', exact: true })
  await field(page, '日均写入').fill('70')
  await expect(action).toBeDisabled(); await expect(page.locator('.result-facts')).toContainText('12.775 TB/年')
  await page.getByRole('button', { name: '重新计算', exact: true }).click()
  await expect(page.locator('.result-facts')).toContainText('25.55 TB/年')
  await action.click()
  await expect(field(page, '目标年限')).toBeFocused(); await expect(field(page, '目标年限')).toHaveValue('5')
  await expect(field(page, '日均写入')).toHaveValue('70')
  await page.getByRole('button', { name: '开始计算', exact: true }).click()
  await expect(result(page)).toHaveText('127.8 TB')
  await page.getByRole('button', { name: '写入预算', exact: true }).click()
  await expect(result(page)).toHaveText('暂不能估算')
  await page.getByRole('button', { name: '补充累计历史', exact: true }).click()
  await expect(field(page, '全寿命累计 Host Writes')).toBeFocused()
  await field(page, '全寿命累计 Host Writes').fill('18.5')
  await page.getByRole('button', { name: '重新计算', exact: true }).click()
  await expect(result(page)).toHaveText('4.3 年')
})

test('P/E unknown history shows total NAND budget without suggesting unused history', async ({ page }) => {
  await page.getByRole('button', { name: 'P/E 工程估算（高级）', exact: true }).click()
  await field(page, '有效循环容量').fill('32'); await field(page, 'P/E 上限').fill('3000')
  await field(page, '已经消耗的写入量来源').selectOption('unknown')
  await field(page, '未来 WAF').fill('2'); await field(page, '日均写入').fill('35')
  await page.getByRole('button', { name: '开始计算', exact: true }).click()
  await expect(page.locator('.result-facts')).toContainText('96 TB NAND')
  await expect(page.locator('.result-facts')).toContainText('12.775 TB/年')
  await expect(page.locator('.chart')).toHaveCount(0)
  await page.getByRole('button', { name: '补充累计历史', exact: true }).click()
  await expect(field(page, '全寿命 NAND 写入')).toBeFocused()
  await expect(field(page, '全寿命 NAND 写入')).toHaveValue('')
})

test('long preset details and filters reflow at 320px and 200% text without overflow', async ({ page }) => {
  await page.getByRole('button', { name: '消费卡', exact: true }).click()
  await field(page, '卡片型号 / 容量（可选）').selectOption('kingston-canvas-sdcs2-16gb')
  await page.getByText('厂商来源与适用条件', { exact: true }).click()
  for (const width of [1440, 1024, 601, 600, 320]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
    await expect(page.locator('.preset-name')).toContainText('已停产')
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.addStyleTag({ content: ':root { font-size: 32px !important; }' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
})

for (const width of [1440, 1360, 1359, 1358, 1164, 1163, 1162, 1101, 1100, 1099, 1024, 865, 864, 863, 672, 671, 670, 601, 600, 599, 550, 432, 431, 430, 320]) {
  test(`reflow ${width}px preserves values and chart without page overflow`, async ({ page }) => {
    await usedA(page); await page.setViewportSize({ width, height: 1000 })
    await expect(result(page)).toHaveText('8.6 年'); await expect(field(page, '日均写入')).toHaveValue('35')
    await expect(page.locator('.recharts-surface')).toBeVisible()
    const geometry = await page.evaluate(() => ({ width: document.documentElement.clientWidth, scroll: document.documentElement.scrollWidth, chartWidth: document.querySelector('.chart').getBoundingClientRect().width }))
    expect(geometry.scroll).toBeLessThanOrEqual(geometry.width); expect(geometry.chartWidth).toBeGreaterThan(150)
    const hostInputWidth = await field(page, '全寿命累计 Host Writes').evaluate(element => element.clientWidth)
    expect(hostInputWidth).toBeGreaterThan(85)
    await page.getByRole('button', { name: '高级设置（可选）', exact: true }).click()
    const dialog = page.getByRole('dialog'); await expect(dialog).toBeVisible()
    const bounds = await dialog.boundingBox(); expect(bounds.x).toBeGreaterThanOrEqual(0); expect(bounds.x + bounds.width).toBeLessThanOrEqual(width)
    await page.getByRole('button', { name: '取消', exact: true }).click()
  })
}
test('200% text enlargement independently reflows; reduced motion and local-only requests', async ({ page }) => {
  const outbound = []
  page.on('request', request => { if (!request.url().startsWith('http://127.0.0.1') && !request.url().startsWith('http://localhost')) outbound.push(request.url()) })
  await page.emulateMedia({ reducedMotion: 'reduce' }); await usedA(page)
  await page.addStyleTag({ content: ':root { font-size: 32px !important; }' })
  await expect(result(page)).toHaveText('8.6 年')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await page.locator('.chart').scrollIntoViewIfNeeded()
  await expect(page.locator('.chart .recharts-xAxis-tick-labels text').first()).toBeVisible()
  await expect.poll(() => page.evaluate(() => {
    const xText = Array.from(document.querySelectorAll('.chart .recharts-xAxis-tick-labels text')).find(node => node.textContent === '现在')
    const yText = Array.from(document.querySelectorAll('.chart .recharts-yAxis-tick-labels text')).find(node => node.textContent === '0')
    return xText.getBoundingClientRect().top - yText.getBoundingClientRect().bottom
  })).toBeGreaterThan(0)
  await page.getByRole('button', { name: '计算原理', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await page.getByRole('button', { name: '计算分析', exact: true }).click()
  await expect(field(page, '日均写入')).toHaveValue('35')
  expect(outbound).toEqual([])
})
