import { help, sources } from './help'

const sections = [['meaning', '结果含义'], ['host', '主机 TBW'], ['selection', '选型需求'], ['pe', 'P/E 工程估算'], ['parameters', '参数取值'], ['sources', '边界与来源']]

export default function Theory({ onReturn }) {
  return <div className="theory-layout"><aside className="theory-sidebar"><details open><summary>计算原理目录</summary><nav aria-label="计算原理目录">{sections.map(([id, title]) => <a key={id} href={`#theory-${id}`}>{title}</a>)}<button type="button" className="button" onClick={onReturn}>返回计算</button></nav></details></aside><article className="theory-content"><h2>计算原理</h2><p>了解参数、验证计算过程，并确认结果的适用范围。</p>
    <section id="theory-meaning" className="panel"><h3>这个工具能算什么？</h3><p>写入预算：还剩多少可写入量，以及在给定自然日负载下预计何时达到预算。<br />选型需求：未来目标周期需要多少主机写入预算，候选卡是否有足够余量。</p><p className="warning-text">时间投影不是失效日期；预算余量不是健康百分比，也不保证断电保持或掉电安全。</p></section>
    <section id="theory-host" className="panel"><h3>主机 TBW：从输入到结果</h3><p className="formula">R_host = max(E_host − H_lifetime, 0)<br />t_days = R_host ÷ (q_GB_per_day ÷ 1000)<br />t_years = t_days ÷ 365</p><p>示例情景：128 − 18.5 = 109.5 TB；109.5 ÷ 0.035 = 3128.571428… 天，约 8.6 年。</p><p>厂商主机 TBW 与累计量必须同口径；厂商评级包含其指定工况，本路径不再除以 WAF。全新卡由你明确选择，已用卡需要完整历史。历史未知不推算现有卡时间；q = 0 时仍可显示剩余预算，不显示无限寿命。达到预算不等于立刻损坏。[S03/S05/S10]</p></section>
    <section id="theory-selection" className="panel"><h3>选型需求：不选候选卡也能计算</h3><p className="formula">E_required = (q_GB_per_day ÷ 1000) × 365 × Y<br />M_candidate = E_candidate_available − E_required</p><p>只填目标年限与日均写入即可。示例情景：35 GB/天 × 5 年 = 63.875 TB；全新候选 128 TB 的余量为 64.125 TB。</p><p>默认比较明确全新卡；已用候选扣除完整 Host 历史，未知历史不显示确定余量。正余量仅表示写入量比较满足，温度、保持与掉电条件需另行核对。日均已含占空比时不再乘开机时长；本版不暗加增长率、安全或冗余系数。</p></section>
    <section id="theory-pe" className="panel"><h3>P/E 工程估算：仅在参数适用时使用</h3><p>P/E（Program / Erase）表示 NAND 的编程 / 擦除循环次数，用来近似评估底层闪存的总磨损预算。普通用户通常无需使用：已有主机 TBW 时选常用方式；只知道日均写入与使用年限时选选型需求。</p><p className="formula">B_NAND ≈ C_pool_TB × PE_limit<br />N_used ≈ H_lifetime × WAF_past（采用历史估算时）<br />R_host ≈ max(B_NAND − N_used, 0) ÷ WAF_future<br />t_days ≈ R_host ÷ (q_GB_per_day ÷ 1000)</p><p>历史 WAF 与未来 WAF 独立。示例情景：0.032 × 3000 = 96 TB NAND；(96 − 38.4) ÷ 2 = 28.8 TB 主机写入；约 822.857142… 天、2.3 年。</p><p>有效循环容量不是默认的卡面容量。需对应同一 NAND 工作模式和循环池，说明 pSLC / TLC、保留区与坏块口径。混合存储池不可直接合并。假设容量换算有效、磨损近似均匀、P/E 与 EOL / 保持要求一致；编程字节不是擦除循环的精确替代品。结果始终是工程近似，不是厂商额定 TBW 或保证；不自动添加 OP、磨损均衡效率或温度系数。[S03/S04/S06/S12]</p></section>
    <section id="theory-parameters" className="panel"><h3>参数怎么填？</h3><dl className="parameter-guide">{Object.entries(help).map(([key, info]) => <div key={key}><dt>{info.title}</dt><dd>{info.body}</dd></div>)}</dl><p>十进制单位：1 TB = 1000 GB；1 GiB = 2³⁰ 字节，1 TiB = 2⁴⁰ 字节。MB/s 和 Mb/s 不混用。中间值不舍入，结果、图表、敏感性与过程取自同一计算快照。</p></section>
    <section id="theory-sources" className="panel"><h3>使用范围与数据来源</h3><p>高级设置补充来源与核对工况，不是基础计算的必填问卷。预设只填已公开且口径适用的参数，手动改动保留为假设；来源已填写不代表工况已验证。</p><p>工作温度范围不等于断电可保持时长。温度、refresh、读扰、ECC、坏块、掉电完整性和日历老化没有统一寿命乘数。Health 百分比不能线性换算成年限，eMMC EXT_CSD 也不是普通 SD 命令。[S01/S02/S05/S11]</p><p>录像小时不直接当作主机 TBW。已知公开测试码率时，测试视频载荷当量 TB = Mbps × hours × 0.00045，仅表示测试载荷，不含已验证设备或文件系统开销。DWPD 需要同时有容量、评级年限和适用条件才能换算。V30 不是录像测试码率。</p><p>SD、SSD 与 eMMC 资料分别限定适用范围，跨介质内容仅作定义和方法参照；不据此补默认耐久值。未获得 JESD218 / JESD219 现行全文，不宣称按现行标准逐条认证。把几年写入压缩到数日，不默认与服役等效。[S12]</p><ul className="sources">{sources.map(([id, title, url, limitation]) => <li key={id}><a href={url} target="_blank" rel="noreferrer" aria-label={`${id} · ${title}（新窗口）`}>{id} · {title}</a><p className="hint">{limitation}</p></li>)}</ul></section>
    <button type="button" className="button primary" onClick={onReturn}>返回计算</button>
  </article></div>
}
